### PR TITLE
Unexpected token u in JSON at position 0

### PR DESCRIPTION
**Pull request by MaiKaY**
Should solve https://github.com/arifulhb/amazon-pa-api50/issues/4

### CODE REVIEW

**Comment by MaiKaY** [comment]
Hi @arifulhb,
could you please review and merge this PR?

**Comment by MaiKaY** [comment]
Hi @arifulhb,
when do you plan to publish the new version (`0.0.4`) to the npm registry?

**Comment by arifulhb** [comment]
@MaiKaY This Friday I'll do it.

**Comment by MaiKaY** [comment]
@arifulhb any updates?

**Comment by fixanoid** [comment]
Hi @arifulhb any luck getting this to npm? Thanks!

**Pull request merged**
